name: Bump Version
on:
  pull_request:
    types: [closed]

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_at != null
    strategy:
      max-parallel: 1
    steps:
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: "fcurella/gh-status-check@main"
        with:
          ignoreContexts: coverage/coveralls,continuous-integration/appveyor/branch
          ignoreActions: autobump
          checkInterval: 12
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Next Part
        id: nextpart
        if: steps.waitforstatuschecks.outputs.status == 'success'
        uses: "fcurella/gh-action-label-to-semver@main"
        with:
          major: "bump-version:major"
          minor: "bump-version:minor"
          defaultPart: "patch"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Get Next Version
        uses: "fcurella/gh-action-next-version@main"
        id: nextversion
        with:
          part: ${{ steps.nextpart.outputs.part }}
      - name: Update Changelog
        uses: "fcurella/gh-action-update-changelog@main"
        with:
          changelogPath: "CHANGELOG.md"
          changelogLine : 3
          currentVersion: ${{ steps.nextversion.outputs.currentVersion }}
          nextVersion: ${{ steps.nextversion.outputs.nextVersion }}
      - name: Bump version
        uses: "fcurella/gh-action-bump2version@main"
        with:
          part: ${{ steps.nextpart.outputs.part }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
